/**
 * Trabble Client Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams }               from '@angular/common/http';

import { Observable }                                        from 'rxjs/Observable';
import '../rxjs-operators';

import { CommonResWithDataModelLoginSuccessResModel } from '../model/commonResWithDataModelLoginSuccessResModel';
import { CommonWithoutDataResModel } from '../model/commonWithoutDataResModel';
import { ExternalLoginModel } from '../model/externalLoginModel';
import { LoginModel } from '../model/loginModel';
import { SignupModel } from '../model/signupModel';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';


@Injectable()
export class AccountService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }



    /**
     * 
     * 
     * @param model 
     */
    public accountExternalLogin(model?: ExternalLoginModel): Observable<CommonResWithDataModelLoginSuccessResModel> {

        let headers = this.defaultHeaders;

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/external-login`, model, 
        {
            headers: headers,
            withCredentials: this.configuration.withCredentials,
        });
    }

    /**
     * 
     * 
     * @param model 
     */
    public accountLogin(model?: LoginModel): Observable<CommonResWithDataModelLoginSuccessResModel> {

        let headers = this.defaultHeaders;

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/login`, model, 
        {
            headers: headers,
            withCredentials: this.configuration.withCredentials,
        });
    }

    /**
     * 
     * 
     * @param model 
     */
    public accountSignup(model?: SignupModel): Observable<CommonResWithDataModelLoginSuccessResModel> {

        let headers = this.defaultHeaders;

        return this.httpClient.post<any>(`${this.basePath}/api/accounts/signup`, model, 
        {
            headers: headers,
            withCredentials: this.configuration.withCredentials,
        });
    }

}
