/**
 * Trabble Client Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NoteResModel } from './noteResModel';


export class CommonResWithDataModelListNoteResModel {
    status?: number;
    data?: Array<NoteResModel>;
    message?: string;
}
