/**
 * Trabble Client Portal API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DropDownOption } from './dropDownOption';


export class PortalScreenColumn {
    bindingPropertyName?: string;
    title?: string;
    type?: string;
    canEdit?: boolean;
    expandedViewOnly?: boolean;
    order?: number;
    portalScreenId?: string;
    dropdownOptions?: Array<DropDownOption>;
    createdAt?: Date;
    updatedAt?: Date;
    deleted?: boolean;
    id?: string;
}
